---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - php7.1-mysql
    - php7.1
    - libapache2-mod-php7.1
    - php7.1-mcrypt
# Mysql
#    - mysql-server
#    - python-mysqldb


